# Generated by Django 6.0.5 on 2026-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.IntegerField(help_text='Trainee_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trianee Name', max_length=100, verbose_name='Name')),
            ],
        ),
    ]
