# Generated by Django 6.0.5 on 2026-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
