# Generated by Django 6.0.5 on 2026-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Trainee_Photo'),
        ),
    ]
