# Generated by Django 6.0.5 on 2026-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
