# Generated by Django 6.0.5 on 2026-05-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='test',
        ),
    ]
