# Generated by Django 6.0.5 on 2026-05-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Code')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('description', models.TextField(null=True)),
                ('Tools', models.CharField(max_length=100, null=True, verbose_name='Course tools')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Insert Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
