# Generated by Django 6.0.5 on 2026-05-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Tools',
            new_name='tool',
        ),
    ]
