# Generated by Django 6.0.5 on 2026-05-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_tools_courses_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='update_date',
        ),
    ]
